name: CI/CD Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  backend-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Trust dev certificates
        run: dotnet dev-certs https --trust

      - name: Run tests
        run: dotnet test --no-build --verbosity minimal

  build-and-push-images:
    needs: backend-integration-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: store-auth
            context: .
            dockerfile: ./src/Services/Auth/Auth.API/Dockerfile

          - name: store-users
            context: .
            dockerfile: ./src/Services/Users/Users.API/Dockerfile

          - name: store-catalog
            context: .
            dockerfile: ./src/Services/Catalog/Catalog.API/Dockerfile

          - name: store-cart
            context: .
            dockerfile: ./src/Services/Cart/Cart.API/Dockerfile

          - name: store-notifications
            context: .
            dockerfile: ./src/Services/Notifications/Notifications.API/Dockerfile

    steps:
      - uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.service.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SHORT_SHA=${{ env.SHORT_SHA }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service.name }}:${{ env.SHORT_SHA }}
