name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Trust the .NET dev certificate
      run: |
        dotnet dev-certs https
        sudo mkdir -p /usr/local/share/ca-certificates/aspnet
        sudo dotnet dev-certs https --export-path /usr/local/share/ca-certificates/aspnet/https.crt --format PEM
        sudo update-ca-certificates
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
